# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [77]:
import numpy as np

In [78]:
a = np.loadtxt('data_minutes_n_ingredients.csv', delimiter = ',', dtype = np.int32, skiprows = 1)
print(a[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [79]:
print(f'среднее значение: {np.mean(a[:, 1:], axis = 0)}')
print(f'минимум: {np.min(a[:, 1:], axis=0)}')
print(f'максимум: {np.max(a[:, 1:], axis = 0)}')
print(f'медиана: {np.median(a[:, 1:], axis = 0)}')

среднее значение: [2.16010017e+04 9.05528000e+00]
минимум: [0 1]
максимум: [2147483647         39]
медиана: [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [80]:
a3 = a[a[:, 1] <= np.quantile(a[:, 1], 0.75)]
a3

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [ 43407,     35,      7],
       [498432,     65,     15],
       [370915,      5,      4]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [81]:
print(f'продолжительность равна нулю: {a[a[:, 1] == 0].shape[0]}')
a[a[:, 1] == 0, 1] = 1
print(f'продолжительность равна нулю 2: {a[a[:, 1] == 0].shape[0]}')

продолжительность равна нулю: 479
продолжительность равна нулю 2: 0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [82]:
np.unique(a[:, 0]).size

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [83]:
print(f'количество {np.unique(a[:, 2]).size}')
print(f'сами значения {np.unique(a[:, 2])}')

количество 37
сами значения [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [84]:
a7 = a[a[:, 2] <= 5]
a7

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [85]:
a8 = a[:, 2] / a[:, 1]
print(f'{a8}')
print(f'максимальное значение: {np.max(a8)}')

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]
максимальное значение: 24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [86]:
np.mean(a[np.argsort(a[:, 1])][-100:, 2])

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [87]:
print(a[np.random.randint(a.shape[0], size = 10)])

[[197096   1230     13]
 [124936     55     16]
 [164059     10      9]
 [419846     23      8]
 [401533     30      6]
 [ 22867     15      8]
 [140994     30     14]
 [ 79171     55     10]
 [ 12604     25      9]
 [360906     25      9]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [91]:
a[a[:, 2] < np.mean(a[:, 2])].shape[0] / a.shape[0] * 100

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [92]:
prost = (a[:, 1] <= 20) & (a[:, 2] <= 5)
a12 = np.hstack((a, prost[:, np.newaxis]))
a12

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [93]:
print(a12[a12[:, 3] == 1].shape[0] / a.shape[0] * 100)

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.